name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'
    - name: Build
      run: |
        IFS="" # Whitespace is NOT an item delimiter!
        export PROJECTS=(
          "CSharpMath Tests"
          "CSharpMath.Editor Tests"
          "CSharpMath.Editor Tests (F♯)"
          "CSharpMath.Rendering Tests"
          "Typography/Typography.TextBreak/Typography.TextBreak.UnitTests"
        )
        for p in ${PROJECTS[*]} do
          dotnet build "$p" -c:Release
        done
    - name: Test
      run: |
        for p in ${PROJECTS[*]} do
          dotnet test "$p"
        done
