name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'
    - name: Build
      run: |
        PROJECTS=("CSharpMath Tests/CSharpMath Tests.csproj"
                  "CSharpMath.Editor Tests/CSharpMath.Editor Tests.csproj"
                  "CSharpMath.Editor Tests (F♯)/CSharpMath.Editor Tests (F♯).csproj"
                  "CSharpMath.Rendering Tests/CSharpMath.Rendering Tests.csproj"
                  "Typography/Typography.TextBreak/Typography.TextBreak.UnitTests/TextBreakTests.csproj")
        for p in ${PROJECTS[*]}; do
          dotnet build "$p" -c:Release
        done
    - name: Test
      run: |
        for p in ${PROJECTS[*]}; do
          dotnet test "$p"
        done
