name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  all_projects:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'
    - name: Build and Test
      run: |
        for p in\
          "CSharpMath.CoreTests"\
          "CSharpMath.Editor.Tests"\
          "CSharpMath.Editor.Tests.FSharp"\
          "CSharpMath.Rendering.Tests"\
          "Typography/Typography.TextBreak/Typography.TextBreak.UnitTests"
        do
          if [[ $p == CSharpMath* ]]
          then # Only CSharpMath test projects can be logged into GitHub
            dotnet add "$p" package GitHubActionsTestLogger
            dotnet build "$p" -c:Release
            dotnet test "$p" -c:Release --logger GitHubActions
          else
            dotnet test "$p" -c:Release
          fi
        done
