name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  all_projects:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    - name: Build and Test
      run: |
        for p in\
          "CSharpMath.CoreTests"\
          "CSharpMath.Editor.Tests"\
          "CSharpMath.Editor.Tests.FSharp"\
          "CSharpMath.Rendering.Tests"\
          "CSharpMath.Rendering.Text.Tests"\
          "CSharpMath.Xaml.Tests"\
          "Typography/Typography.TextBreak/Typography.TextBreak.UnitTests"
        do
          dotnet add "$p" package Microsoft.NET.Test.Sdk # Update is required for GitHubActionsTestLogger to print anything
          dotnet add "$p" package GitHubActionsTestLogger
          dotnet test "$p" --configuration Release --logger GitHubActions
        done
